// Generated by CoffeeScript 1.10.0
(function() {
  var Catalogue, mongoose, penguin, schema;

  mongoose = require('mongoose');
  require('coffee-script/register');
  penguin = require('penguin');

  schema = mongoose.Schema({
    title: {
      type: String,
      required: true
    },
    publish: Boolean,
    date: {
      type: Date,
      default: new Date(),
      $p: {
        widget: 'date'
      }
      //required: true
    },
    content: {
      type: String,
      required: true,
      $p: {
        widget: 'textarea',
        display: 'e'
      }
    },
    /*type: {
      type: String,
    },
    slug: {
      type: String,
      $p: {
        hide: true
      }
    },*/
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Category',
      $p: {
        widget: 'select'
      }
    },
    cover: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'File'
    },
    thumb: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'File'
    }
  });

  schema.pre('save', function(next) {
    var self;
    self = this;
    return penguin.fileManager.fixBase64(this.content, {}, function(err, newContent) {
      if (err) {
        console.log(err);
        return next();
      }
      console.log(">>", newContent);
      self.content = newContent;
      return next();
    });
  });

  Catalogue = mongoose.model('Catalogue', schema);

  Catalogue.$p = {
    hide: true,
    actions: {
      publish: penguin.utils.createSimpleAction({
        published: true
      }),
      unpublish: penguin.utils.createSimpleAction({
        published: false
      })
    },
    rowActions: ['publish', 'unpublish'],
    pageActions: ['_delete', 'publish', 'unpublish'],
    setActions: ['_export_csv'],
    sort: 'title',
    itemsPerPage: 50
  };

  module.exports = Catalogue;

}).call(this);
